CREATE TABLE QUESTION_BANK(
	ID VARCHAR(36) NOT NULL COMMENT 'ID', 
	CODE VARCHAR(100) NOT NULL COMMENT '编码', 
	NAME VARCHAR(300) NOT NULL COMMENT '题库名称', 
	DESCRIPTION VARCHAR(300) COMMENT '题库描述', 
	DELETE_FLAG TINYINT(1) NOT NULL DEFAULT 0 NOT NULL COMMENT '删除标识', 
	PRIMARY KEY(ID)
)COMMENT = '题库表';

CREATE TABLE QUESTION(
	ID VARCHAR(36) NOT NULL COMMENT 'ID', 
	CONTENT VARCHAR(3000) NOT NULL COMMENT '试题内容',
    DIFFICULTY VARCHAR(100) NOT NULL COMMENT '试题难度等级（简单、中等、复杂）',
    TYPE_ VARCHAR(100) NOT NULL COMMENT '试题类（单选题、多选题、判断题、填空题、问答题）', 
	SCORE DOUBLE COMMENT '试题分数', 
	ANSWER VARCHAR(3000) COMMENT '参考答案', 
	EXPLANATION VARCHAR(3000) COMMENT '答案解析', 
	QUESTION_BANK_ID VARCHAR(36) COMMENT '题库ID', 
    DELETE_FLAG TINYINT(1) NOT NULL DEFAULT 0 NOT NULL COMMENT '删除标识', 
	PRIMARY KEY(ID)
) COMMENT = '试题表';
CREATE INDEX QUESTION_DIFFICULTY on QUESTION(DIFFICULTY);
CREATE INDEX QUESTION_TYPE_ on QUESTION(TYPE_);
